services:
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8080:80  # Map host port 8080 to container port 80
    depends_on:
      - backend

  backend:
    build:
      context: backend
      target: builder
